# Generated by Django 6.0.3 on 2026-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='Điểm thưởng Luxury'),
        ),
    ]
